# Generated by Django 2.2.5 on 2019-09-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
    ]
