# Generated by Django 2.2.5 on 2019-09-18 20:21

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(storage=app.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
    ]
